version: 1
disable_existing_loggers: no
formatters:
  default:
    (): Applications.shared.customformatterfactory
handlers:
  file:
    formatter: default
    (): Applications.shared.customfilehandler
    maxbytes: 512000
    backupcount: 3
loggers:
  default:
    level: DEBUG
    handlers: [file]
    propagate: no
root:
  level: DEBUG
  handlers: [file]
