version: 1
disable_existing_loggers: no
formatters:
  default:
    (): Applications.shared.customformatterfactory
handlers:
  file:
    formatter: default
    (): Applications.shared.customfilehandler
    maxbytes: 614400
    backupcount: 6
loggers:
#
# Default logger.
  Default:
    level: DEBUG
    handlers: [file]
    propagate: no
#
# Loggers for Audio CD ripping Application.
  Ripper:
    level: DEBUG
    handlers: [file]
    propagate: no
  Applications.Database.AudioCD:
    level: INFO
    handlers: [file]
    propagate: no
  Applications.AudioCD:
    level: INFO
    handlers: [file]
    propagate: no
#
# Root logger.
root:
  level: DEBUG
  handlers: [file]
