version: 1
disable_existing_loggers: no
formatters:
  default:
    (): Applications.shared.customformatterfactory
handlers:
  file:
    formatter: default
    (): Applications.shared.customfilehandler
    maxbytes: 614400
    backupcount: 6
loggers:
  default:
    level: DEBUG
    handlers: [file]
    propagate: no
  info:
    level: INFO
    handlers: [file]
    propagate: no
  warning:
    level: WARNING
    handlers: [file]
    propagate: no
  audiocd:
    level: DEBUG
    handlers: [file]
    propagate: no
root:
  level: DEBUG
  handlers: [file]
