# -*- coding: ISO-8859-1 -*-
__author__ = 'Xavier ROSSET'


# ===================
# Absolute import(s).
# ===================
import os
import sys
import argparse
import tempfile
import subprocess
from contextlib import contextmanager


# =================
# Arguments parser.
# =================
parser = argparse.ArgumentParser()
parser.add_argument("profile", help="rip profile")
parser.add_argument("-t", "--test", action="store_true")
parser.add_argument("-d", "--debug", action="store_true")
arguments = parser.parse_args()


# ==========
# Functions.
# ==========
@contextmanager
def chgcurdir(d):
    wcdir = os.getcwd()
    os.chdir(d)
    yield
    os.chdir(wcdir)


# ==========
# Constants.
# ==========
DEFAULT = {
    "track1": {'Album': 'Cruelty and the Beast',
               'AlbumArtist': 'Cradle of Filth',
               'AlbumArtistSort': 'Cradle of Filth',
               'Artist': 'Cradle of Filth',
               'ArtistSort': 'Cradle of Filth',
               'Bootleg': 'N',
               'Disc': '1/2',
               'Encoder': 'OptimFROG 4.1003',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Label': 'Atlantic',
               'Live': 'N',
               'Profile': 'Default',
               'Source': 'CD (Lossless)',
               'Style': 'Blues-Rock',
               'Title': 'tenth avenue freeze-out [bonus]',
               'TitleLanguage': 'English',
               'Track': '1/3',
               'UPC': '075678267826',
               'Year': '1970',
               'Z_AlbumSortCount': '1',
               'Z_OrigYear': '1970',
               '_albumart_1_Front Album Cover': 'C:\\Users\\Xavier\\AppData\\Local\\Temp\\dbp133A.tmp\\6.bin'},
    "track2": {'Album': 'Cruelty and the Beast',
               'AlbumArtist': 'Cradle of Filth',
               'AlbumArtistSort': 'Cradle of Filth',
               'Artist': 'Cradle of Filth',
               'ArtistSort': 'Cradle of Filth',
               'Bootleg': 'N',
               'Disc': '1/2',
               'Encoder': '(FLAC 1.3.0)',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Label': 'Atlantic',
               'Live': 'N',
               'Profile': 'Default',
               'Source': 'CD (Lossless)',
               'Style': 'Blues-Rock',
               'Title': 'tenth avenue freeze-out [bonus]',
               'TitleLanguage': 'English',
               'Track': '1/3',
               'UPC': '075678267826',
               'Year': '1970',
               'Z_AlbumSortCount': '1',
               'Z_OrigYear': '1970',
               '_albumart_1_Front Album Cover': 'C:\\Users\\Xavier\\AppData\\Local\\Temp\\dbp133A.tmp\\6.bin'},
    "track3": {'Album': 'Cruelty and the Beast',
               'AlbumArtist': 'Cradle of Filth',
               'AlbumArtistSort': 'Cradle of Filth',
               'Artist': 'Cradle of Filth',
               'ArtistSort': 'Cradle of Filth',
               'Bootleg': 'N',
               'Disc': '1/2',
               'Encoder': 'OptimFROG 4.1003',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Label': 'Atlantic',
               'Live': 'N',
               'Profile': 'Default',
               'Source': 'CD (Lossless)',
               'Style': 'Blues-Rock',
               'Title': 'tenth avenue freeze-out [bonus]',
               'TitleLanguage': 'English',
               'Track': '2/3',
               'UPC': '075678267826',
               'Year': '1970',
               'Z_AlbumSortCount': '1',
               'Z_OrigYear': '1970',
               '_albumart_1_Front Album Cover': 'C:\\Users\\Xavier\\AppData\\Local\\Temp\\dbp133A.tmp\\6.bin'},
    "track4": {'Album': 'Cruelty and the Beast',
               'AlbumArtist': 'Cradle of Filth',
               'AlbumArtistSort': 'Cradle of Filth',
               'Artist': 'Cradle of Filth',
               'ArtistSort': 'Cradle of Filth',
               'Bootleg': 'N',
               'Disc': '1/2',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Label': 'Atlantic',
               'Live': 'N',
               'Profile': 'Default',
               'Source': 'CD (Lossless)',
               'Style': 'Blues-Rock',
               'Title': 'tenth avenue freeze-out [bonus]',
               'TitleLanguage': 'English',
               'Track': '2/3',
               'UPC': '075678267826',
               'Year': '1970',
               'Z_AlbumSortCount': '1',
               'Z_OrigYear': '1970',
               '_albumart_1_Front Album Cover': 'C:\\Users\\Xavier\\AppData\\Local\\Temp\\dbp133A.tmp\\6.bin'},
    "track5": {'Album': 'Cruelty and the Beast',
               'AlbumArtist': 'Cradle of Filth',
               'AlbumArtistSort': 'Cradle of Filth',
               'Artist': 'Cradle of Filth',
               'ArtistSort': 'Cradle of Filth',
               'Bootleg': 'N',
               'Disc': '1/2',
               'Encoder': 'OptimFROG 4.1003',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Label': 'Atlantic',
               'Live': 'N',
               'Profile': 'Default',
               'Source': 'CD (Lossless)',
               'Style': 'Blues-Rock',
               'Title': 'tenth avenue freeze-out [bonus]',
               'TitleLanguage': 'English',
               'Track': '3/3',
               'UPC': '075678267826',
               'Year': '1970',
               'Z_AlbumSortCount': '1',
               'Z_OrigYear': '1970',
               '_albumart_1_Front Album Cover': 'C:\\Users\\Xavier\\AppData\\Local\\Temp\\dbp133A.tmp\\6.bin'},
    "track6": {'Album': 'Cruelty and the Beast',
               'AlbumArtist': 'Cradle of Filth',
               'AlbumArtistSort': 'Cradle of Filth',
               'Artist': 'Cradle of Filth',
               'ArtistSort': 'Cradle of Filth',
               'Bootleg': 'N',
               'Disc': '1/2',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Label': 'Atlantic',
               'Live': 'N',
               'Profile': 'Default',
               'Source': 'CD (Lossless)',
               'Style': 'Blues-Rock',
               'Title': 'tenth avenue freeze-out [bonus]',
               'TitleLanguage': 'English',
               'Track': '3/3',
               'UPC': '075678267826',
               'Year': '1970',
               'Z_AlbumSortCount': '1',
               'Z_OrigYear': '1970',
               '_albumart_1_Front Album Cover': 'C:\\Users\\Xavier\\AppData\\Local\\Temp\\dbp133A.tmp\\6.bin'}
}

BOOTLEGS = {
    "track1": {'AlbumArtistSort': 'Springsteen, Bruce',
               'Artist': 'Bruce Springsteen',
               'ArtistSort': 'Springsteen, Bruce',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Live': 'Y',
               'Profile': 'Bootlegs',
               'Source': 'CD-R',
               'Title': 'Track 1',
               'TitleLanguage': 'English',
               'Track': '1/5',
               'Z_Bonus': 'N',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackTour': 'Wrecking Ball Tour',
               'Z_BootlegTrackYear': '2014-02-15',
               'Z_OrigAlbum': 'Album',
               'Z_Publisher': 'Label',
               'Z_PublisherReference': 'Reference',
               'albumartist': 'Bruce Springsteen And The E Street Band'},
    "track2": {'AlbumArtistSort': 'Springsteen, Bruce',
               'Artist': 'Bruce Springsteen',
               'ArtistSort': 'Springsteen, Bruce',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': '(FLAC 1.3.0)',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Live': 'Y',
               'Profile': 'Bootlegs',
               'Source': 'CD-R',
               'Title': 'Track 1',
               'TitleLanguage': 'English',
               'Track': '1/5',
               'Z_Bonus': 'N',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackTour': 'Wrecking Ball Tour',
               'Z_BootlegTrackYear': '2014-02-15',
               'Z_OrigAlbum': 'Album',
               'Z_Publisher': 'Label',
               'Z_PublisherReference': 'Reference',
               'albumartist': 'Bruce Springsteen And The E Street Band'},
    "track3": {'AlbumArtistSort': 'Springsteen, Bruce',
               'Artist': 'Bruce Springsteen',
               'ArtistSort': 'Springsteen, Bruce',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Live': 'Y',
               'Profile': 'Bootlegs',
               'Source': 'CD-R',
               'Title': 'Track 2',
               'TitleLanguage': 'English',
               'Track': '2/5',
               'Z_Bonus': 'N',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackTour': 'Wrecking Ball Tour',
               'Z_BootlegTrackYear': '2014-02-15',
               'Z_OrigAlbum': 'Album',
               'Z_Publisher': 'Label',
               'Z_PublisherReference': 'Reference',
               'albumartist': 'Bruce Springsteen And The E Street Band'},
    "track4": {'AlbumArtistSort': 'Springsteen, Bruce',
               'Artist': 'Bruce Springsteen',
               'ArtistSort': 'Springsteen, Bruce',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': '(FLAC 1.3.0)',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Live': 'Y',
               'Profile': 'Bootlegs',
               'Source': 'CD-R',
               'Title': 'Track 2',
               'TitleLanguage': 'English',
               'Track': '2/5',
               'Z_Bonus': 'N',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackTour': 'Wrecking Ball Tour',
               'Z_BootlegTrackYear': '2014-02-15',
               'Z_OrigAlbum': 'Album',
               'Z_Publisher': 'Label',
               'Z_PublisherReference': 'Reference',
               'albumartist': 'Bruce Springsteen And The E Street Band'},
    "track5": {'AlbumArtistSort': 'Springsteen, Bruce',
               'Artist': 'Bruce Springsteen',
               'ArtistSort': 'Springsteen, Bruce',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Live': 'Y',
               'Profile': 'Bootlegs',
               'Source': 'CD-R',
               'Title': 'Track 3',
               'TitleLanguage': 'English',
               'Track': '3/5',
               'Z_Bonus': 'N',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackTour': 'Wrecking Ball Tour',
               'Z_BootlegTrackYear': '2014-02-15',
               'Z_OrigAlbum': 'Album',
               'Z_Publisher': 'Label',
               'Z_PublisherReference': 'Reference',
               'albumartist': 'Bruce Springsteen And The E Street Band'},
    "track6": {'AlbumArtistSort': 'Springsteen, Bruce',
               'Artist': 'Bruce Springsteen',
               'ArtistSort': 'Springsteen, Bruce',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': '(FLAC 1.3.0)',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Live': 'Y',
               'Profile': 'Bootlegs',
               'Source': 'CD-R',
               'Title': 'Track 3',
               'TitleLanguage': 'English',
               'Track': '3/5',
               'Z_Bonus': 'N',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackTour': 'Wrecking Ball Tour',
               'Z_BootlegTrackYear': '2014-02-15',
               'Z_OrigAlbum': 'Album',
               'Z_Publisher': 'Label',
               'Z_PublisherReference': 'Reference',
               'albumartist': 'Bruce Springsteen And The E Street Band'},
    "track7": {'AlbumArtistSort': 'Springsteen, Bruce',
               'Artist': 'Bruce Springsteen',
               'ArtistSort': 'Springsteen, Bruce',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Live': 'Y',
               'Profile': 'Bootlegs',
               'Source': 'CD-R',
               'Title': 'Track 4',
               'TitleLanguage': 'English',
               'Track': '4/5',
               'Z_Bonus': 'N',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackTour': 'Wrecking Ball Tour',
               'Z_BootlegTrackYear': '2014-02-15',
               'Z_OrigAlbum': 'Album',
               'Z_Publisher': 'Label',
               'Z_PublisherReference': 'Reference',
               'albumartist': 'Bruce Springsteen And The E Street Band'},
    "track8": {'AlbumArtistSort': 'Springsteen, Bruce',
               'Artist': 'Bruce Springsteen',
               'ArtistSort': 'Springsteen, Bruce',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': '(FLAC 1.3.0)',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Live': 'Y',
               'Profile': 'Bootlegs',
               'Source': 'CD-R',
               'Title': 'Track 4',
               'TitleLanguage': 'English',
               'Track': '4/5',
               'Z_Bonus': 'N',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackTour': 'Wrecking Ball Tour',
               'Z_BootlegTrackYear': '2014-02-15',
               'Z_OrigAlbum': 'Album',
               'Z_Publisher': 'Label',
               'Z_PublisherReference': 'Reference',
               'albumartist': 'Bruce Springsteen And The E Street Band'},
    "track9": {'AlbumArtistSort': 'Springsteen, Bruce',
               'Artist': 'Bruce Springsteen',
               'ArtistSort': 'Springsteen, Bruce',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Rock',
               'InCollection': 'Y',
               'Live': 'Y',
               'Profile': 'Bootlegs',
               'Source': 'CD-R',
               'Title': 'Track 5',
               'TitleLanguage': 'English',
               'Track': '5/5',
               'Z_Bonus': 'N',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackTour': 'Wrecking Ball Tour',
               'Z_BootlegTrackYear': '2014-02-15',
               'Z_OrigAlbum': 'Album',
               'Z_Publisher': 'Label',
               'Z_PublisherReference': 'Reference',
               'albumartist': 'Bruce Springsteen And The E Street Band'},
    "track10": {'AlbumArtistSort': 'Springsteen, Bruce',
                'Artist': 'Bruce Springsteen',
                'ArtistSort': 'Springsteen, Bruce',
                'Bootleg': 'Y',
                'Disc': '1/3',
                'Encoder': '(FLAC 1.3.0)',
                'Genre': 'Rock',
                'InCollection': 'Y',
                'Live': 'Y',
                'Profile': 'Bootlegs',
                'Source': 'CD-R',
                'Title': 'Track 5',
                'TitleLanguage': 'English',
                'Track': '5/5',
                'Z_Bonus': 'N',
                'Z_BootlegTrackCity': 'Melbourne',
                'Z_BootlegTrackCountry': 'Australia',
                'Z_BootlegTrackTour': 'Wrecking Ball Tour',
                'Z_BootlegTrackYear': '2014-02-15',
                'Z_OrigAlbum': 'Album',
                'Z_Publisher': 'Label',
                'Z_PublisherReference': 'Reference',
                'albumartist': 'Bruce Springsteen And The E Street Band'}
}

PJBOOTLEGS = {
    "track1": {'AlbumArtistSort': 'Pearl Jam',
               'Artist': 'Pearl Jam',
               'ArtistSort': 'Pearl Jam',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Alternative Rock',
               'InCollection': 'Y',
               'Profile': 'PJBootlegs /1',
               'Source': 'CD (Lossless)',
               'Title': 'Track 1',
               'TitleLanguage': 'English',
               'Track': '1/2',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackYear': '2014-02-15',
               'albumartist': 'Pearl Jam',
               'Live': 'Y',
               'Year': '2001'},
    "track2": {'AlbumArtistSort': 'Pearl Jam',
               'Artist': 'Pearl Jam',
               'ArtistSort': 'Pearl Jam',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Alternative Rock',
               'InCollection': 'Y',
               'Profile': 'PJBootlegs /1',
               'Source': 'CD (Lossless)',
               'Title': 'Track 1',
               'TitleLanguage': 'English',
               'Track': '1/2',
               'Z_BootlegTrackCity': 'Melbourne',
               'Z_BootlegTrackCountry': 'Australia',
               'Z_BootlegTrackYear': '2014-02-15',
               'albumartist': 'Pearl Jam',
               'Live': 'Y',
               'Year': '2001'},
    "track3": {'AlbumArtistSort': 'Pearl Jam',
               'Artist': 'Pearl Jam',
               'ArtistSort': 'Pearl Jam',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Alternative Rock',
               'InCollection': 'Y',
               'Profile': 'PJBootlegs /1',
               'Source': 'CD (Lossless)',
               'Title': 'Track 2',
               'TitleLanguage': 'English',
               'Track': '2/2',
               'Z_BootlegTrackCity': 'Philadelphia, PA',
               'Z_BootlegTrackCountry': 'United States',
               'Z_BootlegTrackYear': '2013-10-22',
               'albumartist': 'Pearl Jam',
               'Live': 'Y',
               'Year': '2001'},
    "track4": {'AlbumArtistSort': 'Pearl Jam',
               'Artist': 'Pearl Jam',
               'ArtistSort': 'Pearl Jam',
               'Bootleg': 'Y',
               'Disc': '1/3',
               'Encoder': 'FDK v0.1.3',
               'Genre': 'Alternative Rock',
               'InCollection': 'Y',
               'Profile': 'PJBootlegs /1',
               'Source': 'CD (Lossless)',
               'Title': 'Track 2',
               'TitleLanguage': 'English',
               'Track': '2/2',
               'Z_BootlegTrackCity': 'Philadelphia, PA',
               'Z_BootlegTrackCountry': 'United States',
               'Z_BootlegTrackYear': '2013-10-22',
               'albumartist': 'Pearl Jam',
               'Live': 'Y',
               'Year': '2001'}
}

CURDIR = r"G:\Documents\MyPythonProject"


# ===============
# Main algorithm.
# ===============
if arguments.profile == "default":
    d = DEFAULT
elif arguments.profile == "bootlegs":
    d = BOOTLEGS
elif arguments.profile == "pjbootlegs":
    d = PJBOOTLEGS
else:
    sys.exit()
with tempfile.TemporaryDirectory() as tmpdir:
    tagsfile = os.path.join(tmpdir, "tags.txt")
    for i in range(1, len(d)+1):
        cmd = [r"c:\python34\python.exe", "G:\Documents\MyPythonProject\Launchers\CDRipper\AudioCDRipperL.py", tagsfile, arguments.profile]
        with open(tagsfile, "w", encoding="UTF_16LE") as f:
            for j in d["track{0}".format(i)].keys():
                f.write("{}={}\n".format(j, d["track{0}".format(i)][j]))
        with chgcurdir(CURDIR):
            if arguments.test:
                cmd.append("--test")
            if arguments.debug:
                cmd.append("--debug")
            subprocess.call(cmd)
